name: LEMP Server
on:
  push:
    branches:
   # - src
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: apt update command
        run: sudo apt update
      - name: docker compose install
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: docker execute
        run: sudo chmod +x /usr/local/bin/docker-compose
      - name: version check
        run: docker-compose --version
        
      - name: Build the Docker Images
        run: |
         docker-compose build
         
      - name: Build the Docker images
        run: docker-compose build
        
      - name: Logging into the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push the Docker Images to the Docker Hub
        run: docker-compose push
